In [4]:
import numpy as np
import pandas as pd

df_clientes = pd.read_csv("users_data.csv")
df_cartoes = pd.read_csv("cards_data.csv")

df_clientes

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,$37891,$77254,$191349,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,$22681,$33483,$196,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,$163145,$249925,$202328,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,$53797,$109687,$183855,675,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,986,32,70,1987,7,Male,6577 Lexington Lane,40.65,-73.58,$23550,$48010,$87837,703,3
1996,1944,62,65,1957,11,Female,2 Elm Drive,38.95,-84.54,$24218,$49378,$104480,740,4
1997,185,47,67,1973,1,Female,276 Fifth Boulevard,40.66,-74.19,$15175,$30942,$71066,779,3
1998,1007,66,60,1954,2,Male,259 Valley Boulevard,40.24,-76.92,$25336,$54654,$27241,618,1
1999,1110,21,60,1998,11,Female,472 Ocean View Street,42.86,-71.48,$32325,$65909,$181261,673,2

In [5]:
df_cartoes

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,07/2003,2004,No
3,42,825,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,01/2003,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,09/2008,2009,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6141,5361,185,Amex,Credit,300609782832003,01/2024,663,YES,1,$6900,11/2000,2013,No
6142,2711,185,Visa,Credit,4718517475996018,01/2021,492,YES,2,$5700,04/2012,2012,No
6143,1305,1007,Mastercard,Credit,5929512204765914,08/2020,237,NO,2,$9200,02/2012,2012,No
6144,743,1110,Mastercard,Debit,5589768928167462,01/2020,630,YES,1,$28074,01/2020,2020,No
6145,3199,1110,Visa,Credit,4994011318343994,12/2020,120,YES,1,$14400,05/2017,2017,No

In [6]:
print(df_clientes.dtypes)

id                     int64
current_age            int64
retirement_age         int64
birth_year             int64
birth_month            int64
gender                   str
address                  str
latitude             float64
longitude            float64
per_capita_income        str
yearly_income            str
total_debt               str
credit_score           int64
num_credit_cards       int64
dtype: object

In [7]:
print(df_cartoes.dtypes)

id                       int64
client_id                int64
card_brand                 str
card_type                  str
card_number              int64
expires                    str
cvv                      int64
has_chip                   str
num_cards_issued         int64
credit_limit               str
acct_open_date             str
year_pin_last_changed    int64
card_on_dark_web           str
dtype: object

In [8]:
df = pd.merge(df_cartoes, df_clientes, how = "right", left_on = "client_id", right_on = "id")
pd.merge(df_cartoes, df_clientes, how = "right", left_on = "client_id", right_on = "id")

,id_x,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,...,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,...,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,...,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,...,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
3,42,825,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,...,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,...,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6141,5361,185,Amex,Credit,300609782832003,01/2024,663,YES,1,$6900,...,1,Female,276 Fifth Boulevard,40.66,-74.19,$15175,$30942,$71066,779,3
6142,2711,185,Visa,Credit,4718517475996018,01/2021,492,YES,2,$5700,...,1,Female,276 Fifth Boulevard,40.66,-74.19,$15175,$30942,$71066,779,3
6143,1305,1007,Mastercard,Credit,5929512204765914,08/2020,237,NO,2,$9200,...,2,Male,259 Valley Boulevard,40.24,-76.92,$25336,$54654,$27241,618,1
6144,743,1110,Mastercard,Debit,5589768928167462,01/2020,630,YES,1,$28074,...,11,Female,472 Ocean View Street,42.86,-71.48,$32325,$65909,$181261,673,2
6145,3199,1110,Visa,Credit,4994011318343994,12/2020,120,YES,1,$14400,...,11,Female,472 Ocean View Street,42.86,-71.48,$32325,$65909,$181261,673,2

In [9]:
#escolhi a media de idade por cartoes sem repetir ids das mesmas pessoas, 1 pessoa so pode aparecer apenas uma vez, o cartao escolhido é o mastercard
df_mastercard = df[df["card_brand"] == "Mastercard"]

# Contar quantos IDs estão repetidos(mastercard)
total_duplicados = df_mastercard.duplicated(subset=["client_id"]).sum()
print(f"Total de ids duplicados: {total_duplicados}")

df_mastercard_unicos = df_mastercard.drop_duplicates(subset=["client_id"])

media_idade = df_mastercard_unicos["current_age"].mean()
print(f"Média de idade (Mastercard): {media_idade:.2f}")

Total de ids duplicados: 1544
Média de idade (Mastercard): 46.89

In [10]:
grupo_cartoes = df.groupby("card_type")

variabilidade_robusta = grupo_cartoes["current_age"].agg(lambda x: x.quantile(0.75) - x.quantile(0.25))

print("Variabilidade robusta (IQR) da idade por tipo de cartão:")
print(variabilidade_robusta)

#a diferença de idade entre os 25% mais jovens e os 25% mais velhos é de 29 anos

Variabilidade robusta (IQR) da idade por tipo de cartão:
card_type
Credit             27.0
Debit              27.0
Debit (Prepaid)    29.0
Name: current_age, dtype: float64

In [11]:
tabela_contingencia = pd.pivot_table(df,
                                    values="id_x",
                                    index = "gender",
                                    columns="card_type",
                                    aggfunc = "count")

print("Tabela de Contingência (Ocorrências):")
print(tabela_contingencia)

Tabela de Contingência (Ocorrências):
card_type  Credit  Debit  Debit (Prepaid)
gender
Female       1043   1814              282
Male         1014   1697              296

In [12]:
df["yearly_income"] = df["yearly_income"].str.replace("$","").astype(float)

limite_minimo = df.groupby("card_brand")["yearly_income"].min()

print(limite_minimo)

limite_max = limite_minimo.max()

print(limite_max)

renda_media_genero = df.groupby("gender")["yearly_income"].mean()

print(f"Maior valor entre os mínimos das marcas: {limite_max}")
print("\nRenda média por género:")
print(renda_media_genero)

card_brand
Amex          2.0
Discover      2.0
Mastercard    1.0
Visa          1.0
Name: yearly_income, dtype: float64
2.0
Maior valor entre os mínimos das marcas: 2.0

Renda média por género:
gender
Female    45631.877031
Male      44980.758231
Name: yearly_income, dtype: float64

In [13]:
#minusculas
df["card_brand"] = df["card_brand"].str.lower()
#espaços
df["card_brand"] = df["card_brand"].str.strip()

print(df["card_brand"].unique())

<StringArray>
['visa', 'mastercard', 'discover', 'amex']
Length: 4, dtype: str